apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: shopping-cart-production
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: shopping-cart-production
    template:
      metadata:
        labels:
          app: shopping-cart-production
      spec:
        containers:
        - image: quay.io/parashar_singh/do400-deploying-environments:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: shopping-cart-production
          ports:
          - containerPort: 8080
  strategy:
    type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: shopping-cart-production
    name: shopping-cart-production
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: shopping-cart-production
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: shopping-cart-production
    name: shopping-cart-production
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: shopping-cart-production
kind: List
metadata: {}
